USE [AccidentsDW_ETL]
GO

/****** Object:  Table [dbo].[LookupTable]    Script Date: 31.05.2022 20:00:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LookupTable](
	[LookupType] [nvarchar](50) NOT NULL,
	[LookupValue] [nvarchar](100) NOT NULL,
	[LookupName] [nvarchar](100) NOT NULL,
	[LookupID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_LookupTable] PRIMARY KEY CLUSTERED 
(
	[LookupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '0', 'No tow/articulation');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '1', 'Articulated vehicle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '2', 'Double or multiple trailer');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '3', 'Caravan');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '4', 'Single trailer');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '5', 'Other tow');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('TowingArticulation', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '0', 'None');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '1', 'Previous accident');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '2', 'Road works');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '4', 'Parked vehicle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '5', 'Bridge (roof)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '6', 'Bridge (side)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '7', 'Bollard or refuge');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '8', 'Open door of vehicle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '9', 'Central island of roundabout');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '10', 'Kerb');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '11', 'Other object');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '12', 'Any animal (except ridden horse)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '99', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectInCarriageway', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '0', 'Not at or within 20 metres of junction');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '1', 'Approaching junction or waiting/parked at junction approach');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '2', 'Cleared junction or waiting/parked at junction exit');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '3', 'Leaving roundabout');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '4', 'Entering roundabout');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '5', 'Leaving main road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '6', 'Entering main road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '7', 'Entering from slip road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '8', 'Mid Junction - on roundabout or on main road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JunctionLocation', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '0', 'Did not leave carriageway');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '1', 'Nearside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '2', 'Nearside and rebounded');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '3', 'Straight ahead at junction');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '4', 'Offside on to central reservation');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '5', 'Offside on to centrl res + rebounded');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '6', 'Offside - crossed central reservation');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '7', 'Offside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '8', 'Offside and rebounded');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleLeavingCarriageway', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '0', 'None');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '1', 'Skidded');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '2', 'Skidded and overturned');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '3', 'Jackknifed');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '4', 'Jackknifed and overturned');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '5', 'Overturned');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SkiddingOverturning', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '0', 'Did not impact');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '1', 'Front');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '2', 'Back');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '3', 'Offside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '4', 'Nearside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('PointOfImpact', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '0', 'None');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '1', 'Road sign or traffic signal');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '2', 'Lamp post');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '3', 'Telegraph or electricity pole');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '4', 'Tree');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '5', 'Bus stop or bus shelter');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '6', 'Central crash barrier');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '7', 'Near/Offside crash barrier');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '8', 'Submerged in water');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '9', 'Entered ditch');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '10', 'Other permanent object');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '11', 'Wall or fence');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '99', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('HitObjectOffCarriageway', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '1', 'Reversing');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '2', 'Parked');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '3', 'Waiting to go - held up');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '4', 'Slowing or stopping');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '5', 'Moving off');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '6', 'U-turn');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '7', 'Turning left');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '8', 'Waiting to turn left');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '9', 'Turning right');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '10', 'Waiting to turn right');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '11', 'Changing lane to left');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '12', 'Changing lane to right');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '13', 'Overtaking moving vehicle - offside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '14', 'Overtaking static vehicle - offside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '15', 'Overtaking - nearside');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '16', 'Going ahead left-hand bend');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '17', 'Going ahead right-hand bend');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '18', 'Going ahead other');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '99', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleManoeuvre', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '1', 'Journey as part of work');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '2', 'Commuting to/from work');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '3', 'Taking pupil to/from school');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '4', 'Pupil riding to/from school');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '5', 'Other');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '6', 'Not known');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '15', 'Other/Not known');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('JourneyPurpose', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Gender', '1', 'Male');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Gender', '2', 'Female');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Gender', '3', 'Not known');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Gender', '9', 'unknown');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Gender', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '1', '0 - 5');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '2', '6 - 10');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '3', '11 - 15');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '4', '16 - 20');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '5', '21 - 25');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '6', '26 - 35');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '7', '36 - 45');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '8', '46 - 55');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '9', '56 - 65');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '10', '66 - 75');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '11', 'Over 75');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('AgeBand', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '1', 'Pedal cycle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '2', 'Motorcycle 50cc and under');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '3', 'Motorcycle 125cc and under');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '4', 'Motorcycle over 125cc and up to 500cc');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '5', 'Motorcycle over 500cc');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '8', 'Taxi/Private hire car');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '9', 'Car');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '10', 'Minibus (8 - 16 passenger seats)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '11', 'Bus or coach (17 or more pass seats)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '16', 'Ridden horse');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '17', 'Agricultural vehicle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '18', 'Tram');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '19', 'Van / Goods 3.5 tonnes mgw or under');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '20', 'Goods over 3.5t. and under 7.5t');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '21', 'Goods 7.5 tonnes mgw and over');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '22', 'Mobility scooter');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '23', 'Electric motorcycle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '90', 'Other vehicle');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '97', 'Motorcycle - unknown cc');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '98', 'Goods vehicle - unknown weight');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '99', 'Unknown vehicle type (self rep only)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '103', 'Motorcycle - Scooter (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '104', 'Motorcycle (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '105', 'Motorcycle - Combination (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '106', 'Motorcycle over 125cc (1999-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '108', 'Taxi (excluding private hire cars) (1979-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '109', 'Car (including private hire cars) (1979-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '110', 'Minibus/Motor caravan (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '113', 'Goods over 3.5 tonnes (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('VehicleType', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SteeringWheelSide', '1', 'Right');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SteeringWheelSide', '2', 'Left');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SteeringWheelSide', '9', 'Unknown');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SteeringWheelSide', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityClass', '1', 'Driver or rider');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityClass', '2', 'Passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityClass', '3', 'Pedestrian');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '0', 'Pedestrian');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '1', 'Cyclist');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '2', 'Motorcycle 50cc and under rider or passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '3', 'Motorcycle 125cc and under rider or passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '4', 'Motorcycle over 125cc and up to 500cc rider or  passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '5', 'Motorcycle over 500cc rider or passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '8', 'Taxi/Private hire car occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '9', 'Car occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '10', 'Minibus (8 - 16 passenger seats) occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '11', 'Bus or coach occupant (17 or more pass seats)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '16', 'Horse rider');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '17', 'Agricultural vehicle occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '18', 'Tram occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '19', 'Van / Goods vehicle (3.5 tonnes mgw or under) occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '20', 'Goods vehicle (over 3.5t. and under 7.5t.) occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '21', 'Goods vehicle (7.5 tonnes mgw and over) occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '22', 'Mobility scooter rider');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '23', 'Electric motorcycle rider or passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '90', 'Other vehicle occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '97', 'Motorcycle - unknown cc rider or passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '98', 'Goods vehicle (unknown weight) occupant');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '99', 'Unknown vehicle type (self rep only)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '103', 'Motorcycle - Scooter (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '104', 'Motorcycle (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '105', 'Motorcycle - Combination (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '106', 'Motorcycle over 125cc (1999-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '108', 'Taxi (excluding private hire cars) (1979-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '109', 'Car (including private hire cars) (1979-2004)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '110', 'Minibus/Motor caravan (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CasualityType', '113', 'Goods over 3.5 tonnes (1979-1998)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '0', 'Not a bus or coach passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '1', 'Boarding');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '2', 'Alighting');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '3', 'Standing passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '4', 'Seated passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('BusPassenger', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CarPassenger', '0', 'Not car passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CarPassenger', '1', 'Front seat passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CarPassenger', '2', 'Rear seat passenger');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CarPassenger', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('CarPassenger', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('UrbanRuralArea', '1', 'Urban');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('UrbanRuralArea', '2', 'Rural');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('UrbanRuralArea', '3', 'Unallocated');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('UrbanRuralArea', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '1', 'Fine no high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '2', 'Raining no high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '3', 'Snowing no high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '4', 'Fine + high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '5', 'Raining + high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '6', 'Snowing + high winds');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '7', 'Fog or mist');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '8', 'Other');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '9', 'Unknown');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('WeatherCondition', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '1', 'Dry');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '2', 'Wet or damp');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '3', 'Snow');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '4', 'Frost or ice');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '5', 'Flood over 3cm. deep');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '6', 'Oil or diesel');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '7', 'Mud');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadSurfaceCondition', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '0', 'None');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '1', 'Auto traffic signal - out');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '2', 'Auto signal part defective');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '3', 'Road sign or marking defective or obscured');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '4', 'Roadworks');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '5', 'Road surface defective');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '6', 'Oil or diesel');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '7', 'Mud');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('SpecialConditionAtSite', '9', 'unknown (self reported)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '0', 'Not at junction or within 20 metres');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '1', 'Motorway');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '2', 'A(M)');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '3', 'A');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '4', 'B');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '5', 'C');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '6', 'Unclassified');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadClass', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '1', 'Roundabout');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '2', 'One way street');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '3', 'Dual carriageway');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '6', 'Single carriageway');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '7', 'Slip road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '9', 'Unknown');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '12', 'One way street/Slip road');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('RoadType', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '1', 'Daylight');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '4', 'Darkness - lights lit');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '5', 'Darkness - lights unlit');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '6', 'Darkness - no lighting');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '7', 'Darkness - lighting unknown');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('LightCondition', '-1', 'Data missing or out of range');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Severity', '1', 'Fatal');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Severity', '2', 'Serious');
INSERT INTO dbo.LookupTable (LookupType,LookupValue,LookupName) VALUES ('Severity', '3', 'Slight');